# -*- coding: utf-8 -*-
"""Fetch_securities_csv_file.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbXXzUtIzmh0I5S5vbDR5AqcD6lB21Hf
"""

#console commands can be executed by the ‘!’ sign before the command 
! pip install beautifulsoup4 
! pip install requests

import sys
import time
from bs4 import BeautifulSoup
import requests
import pandas as pd
import csv
import shutil

"""# **Problem Statement-01**"""

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.76 Safari/537.36', "Upgrade-Insecure-Requests": "1","DNT": "1","Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","Accept-Language": "en-US,en;q=0.5","Accept-Encoding": "gzip, deflate"}
html = requests.get("https://www.nseindia.com/market-data/securities-available-for-trading",headers=headers)

soup=BeautifulSoup(html.text,'lxml')
urls=[]
filename=[]
for i in soup.find_all('div',class_="tab-pane active", id="tab-q1nar9ur6-0", role="tabpanel"):
  for link in i.find_all('a'):
    urls.append(link.get('href'))
    filename.append(link.contents[0])

filename

urls

for i in range(len(filename)):
  if filename[i]=='Securities available for Equity segment (.csv)':
    required_url = urls[i]
req = requests.get(required_url)
url_content  = req.content
csv_file = open('/content/downloaded.csv','wb')
csv_file.write(url_content)
csv_file.close()

import pandas as pd
df = pd.read_csv('/content/downloaded.csv')
df1 = df['NAME OF COMPANY']
df.drop('NAME OF COMPANY', inplace=True, axis=1)
df1

df.to_csv('/content/req.csv')

for col in df.columns:
    print(col)

"""# **Problem Statement-02**"""

df = pd.read_csv('/content/16DEC2022bhav.csv')
df.drop('Unnamed: 13', inplace=True, axis=1)
df['GAINS'] = 1.000
for i in range(len(df['CLOSE'])):
  df['GAINS'] = (df['CLOSE']-df['OPEN'])/df['OPEN']

df.to_csv('/content/reqinput.csv')

df

for col in df.columns:
    print(col)

df1 = pd.read_csv('/content/downloaded.csv')

for col in df1.columns:
    print(col)

df = df.sort_values(by=['GAINS'] , ascending = False , ignore_index=True)
req = []
for i in range(len(df)):
  if df['SYMBOL'][i] in list(df1['SYMBOL']):
    if len(req)<25:
      req.append([df1['SYMBOL'][i] , df1['NAME OF COMPANY'][i]])

df_req=pd.DataFrame(req,columns=['SYMBOL','NAME OF COMPANY'])

df_req.to_csv('/content/reqoutput_final.csv')

req